export default $doctype({
    // Basic Information Section
    name: $f.Text({
        label: "Name",
        required: 1
    }),
    doctype: $f.Text({
        label: "Doctype",
        required: 1
    }),
    type: $f.Text({
        label: "Type",
        required: 1
    }),
    label: $f.Text({
        label: "Label"
    }),
    description: $f.Text({
        label: "Description"
    }),
    idx: $f.Integer({
        label: "Index",
        default: "0"
    }),

    currency_symbol: {
        type: "Text",
        label: "Currency Symbol"
    },

    // Hide
    hidden: {
        type: "Check",
        label: "Hidden from UI"
    },
    only_db: {
        type: "Check",
        label: "Available in DB Only"
    },

    options: $f.Text({
        label: "Options"
    }),
    filters: $f.JSON({
        label: "Filters"
    }),
    default: $f.Text({
        label: "Default Value"
    }),
    plain: $f.Check({
        label: "Plain"
    }),
    min_length: $f.Integer({
        label: "Min Length"
    }),
    length: $f.Integer({
        label: "Length"
    }),
    min: $f.Integer({
        label: "Min"
    }),
    max: $f.Integer({
        label: "Max"
    }),

    // Reference Section
    reference: $f.Text({
        label: "Reference"
    }),
    reference_type: $f.Select({
        label: "Reference Type",
        options: "Reference\nOne to One\nOne to Many",
        default: "Reference"
    }),
    reference_alias: $f.Text({
        label: "Reference Alias",
        description: "The alias of the reference field. This is used to set the alias of the reference field in the query."
    }),
    reference_label: $f.Text({
        label: "Reference Label",
        description: "The label of the reference field. This is used to set the label of the reference field in the query."
    }),
    below_field: $f.Text({
        label: "Below Field"
    }),
    is_auto_generated: $f.Check({
        label: "Auto Generated",
        description: "If checked, the field will be auto generated by the system."
    }),

    required: $f.Check({
        label: "Required",
        required: 1,
        default: "0"
    }),
    unique: $f.Check({
        label: "Unique"
    }),
    group: $f.Text({
        label: "Group"
    }),
    readonly: $f.Check({
        label: "Read Only"
    }),
    only_create: $f.Check({
        label: "Only Create"
    }),
    allow_on_submit: $f.Check({
        label: "Allow on Submit"
    }),

    in_list_view: $f.Check({
        label: "Show in List View"
    }),


    no_copy: $f.Check({
        label: "No Copy"
    }),
    no_print: $f.Check({
        label: "No Print"
    }),
    is_public: $f.Check({
        label: "Public (For File Field)"
    }),
    accept: $f.Text({
        label: "Accept"
    }),

    on_delete: {
        type: "Select",
        options: "CASCADE\nSET NULL\nSET DEFAULT\nNO ACTION",
        default: "CASCADE"
    },

    depends_on: {
        type: "Code"
    },
    required_on: {
        type: "Code"
    },
    readonly_on: {
        type: "Code"
    },

    // Fetch Section
    fetch_from: {
        type: "Virtual Reference",
        reference: "zodula__Doctype",
    },
    fetch_field: {
        type: "Text",
    },

    width: {
        type: "Integer",
        label: "Width"
    }

}, {
    label: "Field",
    is_system_generated: 1
})

    .on("after_cancel", () => { })