export default $doctype({
    // Basic Information Section
    name: $f.Text({
        label: "Name",
        required: 1
    }),
    doctype: $f.Text({
        label: "Doctype",
        required: 1
    }),
    type: $f.Text({
        label: "Type",
        required: 1
    }),
    label: $f.Text({
        label: "Label"
    }),
    description: $f.Text({
        label: "Description"
    }),
    idx: $f.Integer({
        label: "Index",
        default: "0"
    }),

    // Hide
    hidden: {
        type: "Check",
        label: "Hidden from UI"
    },
    only_db: {
        type: "Check",
        label: "Available in DB Only"
    },

    options: $f.Text({
        label: "Options"
    }),
    filters: $f.JSON({
        label: "Filters"
    }),
    sort: {
        type: "Text",
        label: "Sort"
    },
    order: {
        type: "Text",
        label: "Order"
    },
    default: $f.Text({
        label: "Default Value"
    }),
    plain: $f.Check({
        label: "Plain"
    }),
    min_length: $f.Integer({
        label: "Min Length"
    }),
    length: $f.Integer({
        label: "Length"
    }),
    min: $f.Integer({
        label: "Min"
    }),
    max: $f.Integer({
        label: "Max"
    }),

    // Reference Section
    reference: $f.Text({
        label: "Reference"
    }),
    is_auto_generated: $f.Check({
        label: "Auto Generated",
        description: "If checked, the field will be auto generated by the system."
    }),

    required: $f.Check({
        label: "Required",
        required: 1,
        default: "0"
    }),
    unique: $f.Check({
        label: "Unique"
    }),
    group: $f.Text({
        label: "Group"
    }),
    readonly: $f.Check({
        label: "Read Only"
    }),
    only_create: $f.Check({
        label: "Only Create"
    }),
    allow_on_submit: $f.Check({
        label: "Allow on Submit"
    }),

    in_list_view: $f.Check({
        label: "Show in List View"
    }),


    no_copy: $f.Check({
        label: "No Copy"
    }),
    no_print: $f.Check({
        label: "No Print"
    }),
    is_public: $f.Check({
        label: "Public (For File Field)"
    }),
    accept: $f.Text({
        label: "Accept"
    }),

    // on_delete: {
    //     type: "Select",
    //     options: "CASCADE\nSET NULL\nSET DEFAULT\nNO ACTION",
    //     default: "CASCADE"
    // },

    depends_on: {
        type: "Code"
    },
    required_on: {
        type: "Code"
    },
    readonly_on: {
        type: "Code"
    },

    // Fetch Section
    fetch_from: {
        type: "Text",
    },

    width: {
        type: "Integer",
        label: "Width"
    },
    in_quick_entry: {
        type: "Check",
        label: "In Quick Entry"
    },
    perm_level: {
        type: "Select",
        label: "Permission Level",
        options: "0\n1\n2\n3\n4\n5",
        default: "0"
    },
    only_once: {
        type: "Check",
        label: "Only Once"
    },
    no_translate: {
        type: "Check",
        label: "No Translate"
    }

}, {
    label: "Field",
    is_system_generated: 1,
    is_global: 1,
})

    .on("after_cancel", () => { })