export default $doctype({
    // Basic Information Section
    name: {
        type: "Text",
        label: "Name",
        required: 1
    },
    doctype: {
        type: "Text",
        label: "Doctype",
        required: 1
    },
    type: {
        type: "Text",
        label: "Type",
        required: 1
    },
    label: {
        type: "Text",
        label: "Label"
    },
    description: {
        type: "Text",
        label: "Description"
    },
    idx: {
        type: "Integer",
        label: "Index",
        default: "0"
    },

    // Hide
    hidden: {
        type: "Check",
        label: "Hidden from UI"
    },
    only_db: {
        type: "Check",
        label: "Available in DB Only"
    },

    options: {
        type: "Text",
        label: "Options"
    },
    filters: {
        type: "JSON",
        label: "Filters"
    },
    sort: {
        type: "Text",
        label: "Sort"
    },
    order: {
        type: "Text",
        label: "Order"
    },
    default: {
        type: "Text",
        label: "Default Value"
    },
    plain: {
        type: "Check",
        label: "Plain"
    },
    min_length: {
        type: "Integer",
        label: "Min Length"
    },
    length: {
        type: "Integer",
        label: "Length"
    },
    min: {
        type: "Integer",
        label: "Min"
    },
    max: {
        type: "Integer",
        label: "Max"
    },

    // Reference Section
    reference: {
        type: "Text",
        label: "Reference"
    },
    is_auto_generated: {
        type: "Check",
        label: "Auto Generated",
        description: "If checked, the field will be auto generated by the system."
    },

    required: {
        type: "Check",
        label: "Required",
        required: 1,
        default: "0"
    },
    unique: {
        type: "Check",
        label: "Unique"
    },
    group: {
        type: "Text",
        label: "Group"
    },
    readonly: {
        type: "Check",
        label: "Read Only"
    },
    only_create: {
        type: "Check",
        label: "Only Create"
    },
    allow_on_submit: {
        type: "Check",
        label: "Allow on Submit"
    },

    in_list_view: {
        type: "Check",
        label: "Show in List View"
    },
    in_tree_view: {
        type: "Check",
        label: "Show in Tree View"
    },


    no_copy: {
        type: "Check",
        label: "No Copy"
    },
    no_print: {
        type: "Check",
        label: "No Print"
    },
    is_public: {
        type: "Check",
        label: "Public (For File Field)"
    },
    accept: {
        type: "Text",
        label: "Accept"
    },

    // on_delete: {
    //     type: "Select",
    //     options: "CASCADE\nSET NULL\nSET DEFAULT\nNO ACTION",
    //     default: "CASCADE"
    // },

    depends_on: {
        type: "Code"
    },
    required_on: {
        type: "Code"
    },
    readonly_on: {
        type: "Code"
    },

    // Fetch Section
    fetch_from: {
        type: "Text",
    },

    width: {
        type: "Integer",
        label: "Width"
    },
    height: {
        type: "Integer",
        label: "Height"
    },
    in_quick_entry: {
        type: "Check",
        label: "In Quick Entry"
    },
    perm_level: {
        type: "Select",
        label: "Permission Level",
        options: "0\n1\n2\n3\n4\n5",
        default: "0"
    },
    only_once: {
        type: "Check",
        label: "Only Once"
    },
    no_translate: {
        type: "Check",
        label: "No Translate"
    },
    is_quick_filter: {
        type: "Check",
        label: "Is Quick Filter"
    }

}, {
    label: "Field",
    is_system_generated: 1,
})

    .on("after_cancel", () => { })
